Create CONTRIBUTING.md
Imageomics/ai-explainability pull request #3
Opened 2023-04-04 22:57 UTC by thompsonmj

This is a draft for a document offering advice on how to make a contribution to a collaborative repository.

2023-04-05 00:11 UTC, hlapp requested changes
As written, this assumes that the prospective contributor will have write access and will thus likely be an Imageomics member. That's fine because it is by far the most likely situation, but given that the repo is public-facing, the document should at least clearly say so.

If you created this off of a template, you should probably credit that somewhere.

2023-04-05 00:11 UTC, hlapp commented on CONTRIBUTING.md
> +7. **Push your new branch to the remote.** This should contain any updates made by others as well as your new changes.
Shouldn't this give the command for executing the push? (In part because one will want to include `--set-upstream` if item 8 is expected, as opposed to assuming the PR is complete.)

2023-04-05 00:11 UTC, hlapp commented on CONTRIBUTING.md
> +9. **Open a Pull Request.** On the GitHub repo page, click the "Pull requests tab, click the "New pull requests" button, select the new branch you pushed as the head branch and keep the base branch a
PRs marked as draft are rarely used solicit early feedback (normally, that's what soliciting a review is for). Instead, marking them as in draft stage is usually precisely because feedback is not yet considered useful, for example because the code isn't fully working yet, or is still missing something that the author is well aware of.

2023-04-05 13:59 UTC, thompsonmj commented on CONTRIBUTING.md
> +9. **Open a Pull Request.** On the GitHub repo page, click the "Pull requests tab, click the "New pull requests" button, select the new branch you pushed as the head branch and keep the base branch a
How about this comment on draft PRs then (or I can remove it): "If your work is still in progress, you can also use draft PRs for visibility into the work or facilitate discussion."

2023-04-05 17:06 UTC, hlapp commented on CONTRIBUTING.md
> +9. **Open a Pull Request.** On the GitHub repo page, click the "Pull requests tab, click the "New pull requests" button, select the new branch you pushed as the head branch and keep the base branch a
Yes. Just a small quibble with the wording, I'd use "set PR to draft status" (or similar) instead of "use a draft PR", because the latter can sound like a draft PR and "real" PR might be two different things, when they're really not. "Draft" is just a marker on what's otherwise the same animal.

2023-04-05 18:07 UTC, thompsonmj commented
Made the requested updates summarized in the last commit and did a bit of additional formatting for readability. 
This didn't stem from any single template; rather tips and concepts integrated from blogs and docs so that "any resemblance to existing templates, living or dead, is purely coincidental."

2023-04-05 18:14 UTC, thompsonmj commented
And added a visual diagram at the end.

2023-04-07 17:44 UTC, hlapp commented
@thompsonmj BTW if you're with changes, you need to re-request review. (Otherwise I'll assume you're not done yet.)

2023-04-08 20:30 UTC, hlapp approved these changes
Looks good overall. Two comments/suggestions:
- I've added "shell" format markers as change suggestions to the fenced code blocks where the formatting can help (such as to distinguish command from same-line or following-line comment). (You can accept the suggestions, or make them yourself, or decide to reject them.)
- I've tried but cannot discern any effect of the `<br>` HTML code  at the end of headings when looking at the GitHub-produced rendering. Arguably, this is what should count, even if you have a local editor in which it does seem to make a difference. So, given that, and given that standard Markdown should be preferable unless clearly insufficient, I'd strongly suggest to remove those `<br>`s.

I'm marking this as _approved_ though, because the remaining suggested changes are trivial (and not mandatory), and I believe currently this repository isn't set to invalidate a PR approval if it is followed by additional change(s).

2023-04-08 20:30 UTC, hlapp commented on CONTRIBUTING.md
> +```
```suggestion
```sh
```

2023-04-08 20:30 UTC, hlapp commented on CONTRIBUTING.md
> +```
```suggestion
```sh
```

2023-04-08 20:30 UTC, hlapp commented on CONTRIBUTING.md
> +```
```suggestion
```sh
```

2023-04-08 23:07 UTC, thompsonmj commented
The ` ```sh` is nice, thanks for noting that! 

For the `<br>`s, the purpose was to get the _pro-tip_ lines to show up on a new line (though it does seem I added more than were needed for this). I was just using the GitHub editor, and when I do a preview on the following as typed in the editor:

![image](https://user-images.githubusercontent.com/31709066/230746072-c61a2bf0-f736-4ebf-b2c3-e6a8b35cc7b8.png)
![image](https://user-images.githubusercontent.com/31709066/230746081-598e97ba-48ca-4503-8a21-85076a17f8cf.png)

2023-04-09 01:21 UTC, merged